# Generated by Django 4.1.3 on 2022-11-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_rename_deascriptions_contactus_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=models.CharField(choices=[('Park', 'Park'), ('Hotel', 'Hotel'), ('Resturant', 'Resturant'), ('School', 'School'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(max_length=255, upload_to='product/image'),
        ),
    ]
