# Generated by Django 4.1.3 on 2022-11-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_alter_product_for_what'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=models.CharField(choices=[('School', 'School'), ('Park', 'Park'), ('Resturant', 'Resturant'), ('Hotel', 'Hotel'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(max_length=255, null=True, upload_to='image/'),
        ),
    ]
