# Generated by Django 4.1.3 on 2022-11-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_product_for_what_alter_product_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_what',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Other', 'Other'), ('School', 'School'), ('Park', 'Park'), ('Resturant', 'Resturant')], default='Other', max_length=100),
        ),
    ]
